version: '3'

services:
  products-api:
    build: ./products-api
    ports:
      - "1902:1902"
    depends_on:
      - products-db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: products-db
      DB_PORT: 3306
      DB_DATABASE: funiber_products_test
      DB_USERNAME: root
      DB_PASSWORD: funiber-2@24

  products-webapp:
    build: ./products-webapp
    ports:
      - "9000:80"

  products-db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'funiber_products_test'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'funiber-2@24'
      MYSQL_ROOT_PASSWORD: 'funiber-2@24'
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: products-db
      MYSQL_ROOT_PASSWORD: funiber-2@24
